language: dart
dist: xenial
addons:
  apt:
    packages:
before_install:
  - chmod +x scripts/runTests.sh
install:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
  - pip install --user coverage
script:
  - ./scripts/runTests.sh
cache:
  directories:
    - $HOME/.pub-cache